name: Lập trình cuộc sống
description: Chỉ là blog của một thằng coder
seo_description: Lập trình cuộc sống, blog  về kỹ thuật, rèn luyện kỹ năng và chia sẻ  kinh nghiệm phát triển bản thân dành cho tất cả lập trình viên
avatar: images/logo.gif
baseurl: 
site_url: "http://laptrinhcuocsong.com"
default_post_avatar: images/logo.gif
permalink: /:title.html
version: v1.2.0
markdown: kramdown
syntax_highlighter: rouge
category_configs:
  -
    name: Chuyện lập trình
    url: chuyen-lap-trinh.html
  -
    name: Chuyện nghề nghiệp
    url: chuyen-nghe-nghiep.html
  -
    name: Chuyện bên lề
    url: chuyen-ben-le.html
  -
    name: Linux ubuntu
    url: linux-ubuntu.html
  -
    name: Chuyện cuộc sống
    url: chuyen-cuoc-song.html

tags_config:
  hacking-co-ban:
    name: Hacking cơ bản
  hoc-hack-co-ban:
    name: Học hack cơ bản
  hoc-ubuntu:
    name: Học ubuntu
  lap-trinh-game-bang-javascript:
    name: Lập trình game javascript
  lap-trinh-javascript:
    name: Lập trình javascript
  lap-trinh-mot-game-don-gian:
    name: Lập trình game đơn giản
  tu-hoc-linux:
    name: Tự học linux
  jquery:
    name: Jquery
  kinh-nghiem-phong-van-xin-viec-cntt:
    name: Kinh nghiệm phỏng vấn
  lap-trinh-php:
    name: Lập trình php
  lap-trinh-web:
    name: Lập trình web
  live-stream-lap-trinh:
    name: Live stream lập trình
  cach-tro-thanh-hacker-mu-den:
    name: Cách trở thành hacker mũ đen
  day-lam-hacker-tu-a-z:
    name: Dạy làm hacker từ A đến Z
  doi-song-lap-trinh-vien:
    name: Đời sống lập trình viên
sass:
  style: :compressed
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
defaults:
  values:
    layout: "post"
# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CNAME
  
# paginate
paginate: 15
